/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinaljorgebueso;

import java.io.File;
import javax.swing.JFileChooser;
import javax.xml.xpath.XPathConstants;

/**
 *
 * @author jorge
 */
public class VentanaPF extends javax.swing.JFrame 
{

    /**
     * Creates new form VentanaPF
     */
    Sax GesSax ;
//  Jaxb GesJAXB = new Jaxb();
    ejecutarXpath GesXpath ;
    File ficheroSeleccionado ; 
    
  /*   
    String anteriorA1889 = "/personajes/personaje[@fecha_primera_aparicion < 1889 ]";
   
    String sherlock = "/personajes/personaje[@nombre='Sherlock Holmes']";
   
 */   
    
    
    public VentanaPF() 
    {
        initComponents();
        botonImprimir.setVisible(false);
        jRadioTodosLosNombres.setVisible(false);
        GesSax = new Sax();
 //   Jaxb GesJAXB = new Jaxb();
         GesXpath = new ejecutarXpath();
    }
   
  private File seleccionaFichero()
  {
        File fichero = null;
        int rv;
        JFileChooser fc = new JFileChooser();
        fc.setMultiSelectionEnabled(false);
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        rv = fc.showOpenDialog(this);
      
//        try
//        {
            if(rv == JFileChooser.APPROVE_OPTION)
            {
  //              ficheroSeleccionado = fc.getSelectedFile();
                fichero = fc.getSelectedFile();
            }
            
//        }catch(Exception e)
//        {
//      return ficheroSeleccionado;
//       }
        
        return fichero;
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAbrir = new javax.swing.JButton();
        botonImprimir = new javax.swing.JButton();
        pantallaExito = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PantallaResultado = new javax.swing.JTextArea();
        jRadioTodosLosNombres = new javax.swing.JRadioButton();
        pantallaNombre = new javax.swing.JEditorPane();
        botonAnyadir = new javax.swing.JButton();
        jLabelLibro_origen = new javax.swing.JLabel();
        pantallaLibroOrigen = new javax.swing.JEditorPane();
        jLabelCreador = new javax.swing.JLabel();
        pantallaCreador = new javax.swing.JEditorPane();
        jLabelPrimeraAparicion = new javax.swing.JLabel();
        pantallaPrimeraAparicion = new javax.swing.JEditorPane();
        jLabelEpoca = new javax.swing.JLabel();
        pantallaEpoca = new javax.swing.JEditorPane();
        jLabelActor = new javax.swing.JLabel();
        pantallaActor = new javax.swing.JEditorPane();
        jLabelUltAparicion = new javax.swing.JLabel();
        pantallaUltAparicion = new javax.swing.JEditorPane();
        jLabelAdaptacionSerie = new javax.swing.JLabel();
        PantallaSerie = new javax.swing.JEditorPane();
        jLabelAdapacionPelicula = new javax.swing.JLabel();
        pantallaPelicula = new javax.swing.JEditorPane();
        jLabelEstetica = new javax.swing.JLabel();
        pantallaEstetica = new javax.swing.JEditorPane();
        jLabelViejoCreador = new javax.swing.JLabel();
        TextViejoCreador = new javax.swing.JEditorPane();
        jLabelNuevoCreador = new javax.swing.JLabel();
        TextNuevoCreador = new javax.swing.JEditorPane();
        botonModificar = new javax.swing.JButton();
        botonEjecutaConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAbrir.setText("Abrir");
        botonAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAbrirMousePressed(evt);
            }
        });

        botonImprimir.setText("ImprimeTodo");
        botonImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonImprimirMousePressed(evt);
            }
        });

        pantallaExito.setText("Exito");

        jLabelNombre.setText("nombre");

        PantallaResultado.setColumns(20);
        PantallaResultado.setRows(5);
        jScrollPane1.setViewportView(PantallaResultado);

        jRadioTodosLosNombres.setText("Todos los nombres");
        jRadioTodosLosNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioTodosLosNombresMousePressed(evt);
            }
        });

        botonAnyadir.setText("Añadir");
        botonAnyadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAnyadirMousePressed(evt);
            }
        });

        jLabelLibro_origen.setText("libro_origen");

        jLabelCreador.setText("creador");

        jLabelPrimeraAparicion.setText("primeraAparicion");

        jLabelEpoca.setText("epocaEnLaQueTranscurre");

        jLabelActor.setText("actorUltimaAparicion");

        jLabelUltAparicion.setText("ultimaAparicion");

        jLabelAdaptacionSerie.setText("adaptacionSerie");

        jLabelAdapacionPelicula.setText("adaptacionPelicula");

        jLabelEstetica.setText("estetica");

        jLabelViejoCreador.setText("viejo Creador");

        jLabelNuevoCreador.setText("nuevoCreador");

        botonModificar.setText("Modificar");
        botonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonModificarMousePressed(evt);
            }
        });

        botonEjecutaConsulta.setText("EjecutarConsulta");
        botonEjecutaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonEjecutaConsultaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonAbrir)
                                .addGap(32, 32, 32)
                                .addComponent(jRadioTodosLosNombres))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextViejoCreador)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelViejoCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(172, 172, 172)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextNuevoCreador)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelNuevoCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAnyadir))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelAdapacionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pantallaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelEstetica, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pantallaEstetica, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(pantallaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelLibro_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(pantallaLibroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelPrimeraAparicion)
                                                .addComponent(jLabelCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pantallaCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pantallaPrimeraAparicion))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelActor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(pantallaActor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(59, 59, 59)
                                            .addComponent(jLabelAdaptacionSerie)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(PantallaSerie))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jLabelEpoca)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(pantallaEpoca, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(51, 51, 51)
                                            .addComponent(jLabelUltAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(pantallaUltAparicion)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonImprimir)
                                .addGap(4, 4, 4)
                                .addComponent(botonEjecutaConsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pantallaExito))
                            .addComponent(botonModificar))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAbrir)
                    .addComponent(jRadioTodosLosNombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNombre)
                            .addComponent(pantallaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLibro_origen)
                            .addComponent(pantallaLibroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPrimeraAparicion)
                            .addComponent(pantallaPrimeraAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCreador)
                            .addComponent(pantallaCreador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAdaptacionSerie)
                            .addComponent(PantallaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelEpoca)
                            .addComponent(pantallaEpoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUltAparicion)
                            .addComponent(pantallaUltAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelActor)
                            .addComponent(pantallaActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pantallaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstetica)
                    .addComponent(pantallaEstetica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdapacionPelicula, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                                .addComponent(jLabelViejoCreador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextViejoCreador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelNuevoCreador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextNuevoCreador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(botonModificar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonImprimir)
                            .addComponent(pantallaExito)
                            .addComponent(botonEjecutaConsulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAnyadir)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAbrirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirMousePressed
        botonImprimir.setVisible(true);
        jRadioTodosLosNombres.setVisible(true);
        ficheroSeleccionado = seleccionaFichero();
        int usaSax = GesSax.abrir_XML_SAX(ficheroSeleccionado);
        if(usaSax == 0)
        {
            pantallaExito.setText("SE HA ENCONTRADO EL FICHERO");
        }else if(usaSax == -1)
        {
            pantallaExito.setText("NO SE HA ENCONTRADO EL FICHERO");
        }
    }//GEN-LAST:event_botonAbrirMousePressed

    private void botonImprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImprimirMousePressed
               
        PantallaResultado.setText(GesSax.recorrerSAX());
        
    }//GEN-LAST:event_botonImprimirMousePressed

    private void jRadioTodosLosNombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioTodosLosNombresMousePressed
        GesXpath.ejecutaXPath("/pesonajes/personaje/@nombre");
        PantallaResultado.setText(GesXpath.salida);
    }//GEN-LAST:event_jRadioTodosLosNombresMousePressed

    private void botonEjecutaConsultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEjecutaConsultaMousePressed
        
    }//GEN-LAST:event_botonEjecutaConsultaMousePressed

    private void botonAnyadirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnyadirMousePressed
        //si alguna cuadrícula está vacia no deja añadir un nuevo personaje
        if(pantallaNombre.getText().equals("") || pantallaLibroOrigen.getText().equals("") || pantallaPrimeraAparicion.getText().equals("")
                || pantallaCreador.getText().equals("") || pantallaPelicula.getText().equals("") 
                || PantallaSerie.getText().equals("") || pantallaEstetica.getText().equals("") || pantallaEpoca.getText().equals("") 
                || pantallaUltAparicion.getText().equals("") || pantallaActor.getText().equals(""))
        {
        pantallaExito.setText("Alguna cuadrícula vacía");
        }
        
   //     si están todos las cuadrículas rellenas , coge los valores puestos en cada cuadrícula
        else
        {
          pantallaExito.setText("rellenadas las cuadrículas correctamente ");

            
          GesXpath.anyadirDOM(pantallaNombre.getText(), pantallaLibroOrigen.getText(), 
                  pantallaPrimeraAparicion.getText(),pantallaCreador.getText(), 
                  pantallaPelicula.getText(),PantallaSerie.getText(), pantallaEstetica.getText(),
                  pantallaEpoca.getText(),pantallaUltAparicion.getText(), pantallaActor.getText());
          
          System.out.print("pasa del añadir");
   //usando DOM , GUARDO LOS VALORES PUESTOS EN LAS CUADRÍCULAS, EN EL FICHERO. Tengo que ver si salgo , que se guarde.
         GesXpath.guardarDOMcomoFILE(ficheroSeleccionado.getAbsolutePath());
   //usando el SAX lo vuelvo a abrir el fichero  
         GesSax.abrir_XML_SAX(ficheroSeleccionado);
   //y con el SAX de nuevo, lo imprimo por PantallaResultado
         PantallaResultado.setText(GesSax.recorrerSAX());
        }
    }//GEN-LAST:event_botonAnyadirMousePressed

    private void botonModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModificarMousePressed
//      String cogeNuevo = TextNuevoCreador.getText();
//        for(int i = 0; i<GesJAXB.personaje.size(); i++)
//        {
//            if(GesJAXB.personaje.get(i).get().equals(cogeNuevo))
//            {
//                
//                GesJAXB.personaje.get(i).setCreador(TextNuevoCreador.getText());
//           
//            }
//            
//        }
//        GesJAXB.guardar_XML_JAXB(ficheroSeleccionado);
    }//GEN-LAST:event_botonModificarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() {
                new VentanaPF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea PantallaResultado;
    private javax.swing.JEditorPane PantallaSerie;
    private javax.swing.JEditorPane TextNuevoCreador;
    private javax.swing.JEditorPane TextViejoCreador;
    private javax.swing.JButton botonAbrir;
    private javax.swing.JButton botonAnyadir;
    private javax.swing.JButton botonEjecutaConsulta;
    private javax.swing.JButton botonImprimir;
    private javax.swing.JButton botonModificar;
    private javax.swing.JLabel jLabelActor;
    private javax.swing.JLabel jLabelAdapacionPelicula;
    private javax.swing.JLabel jLabelAdaptacionSerie;
    private javax.swing.JLabel jLabelCreador;
    private javax.swing.JLabel jLabelEpoca;
    private javax.swing.JLabel jLabelEstetica;
    private javax.swing.JLabel jLabelLibro_origen;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNuevoCreador;
    private javax.swing.JLabel jLabelPrimeraAparicion;
    private javax.swing.JLabel jLabelUltAparicion;
    private javax.swing.JLabel jLabelViejoCreador;
    private javax.swing.JRadioButton jRadioTodosLosNombres;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane pantallaActor;
    private javax.swing.JEditorPane pantallaCreador;
    private javax.swing.JEditorPane pantallaEpoca;
    private javax.swing.JEditorPane pantallaEstetica;
    private javax.swing.JLabel pantallaExito;
    private javax.swing.JEditorPane pantallaLibroOrigen;
    private javax.swing.JEditorPane pantallaNombre;
    private javax.swing.JEditorPane pantallaPelicula;
    private javax.swing.JEditorPane pantallaPrimeraAparicion;
    private javax.swing.JEditorPane pantallaUltAparicion;
    // End of variables declaration//GEN-END:variables
}
